### ISSUE TITLE
Change repo description

### ISSUE THREAD

**Issue by coke** [lizmat/rak#2]
`  "description": "Plumbing to be able to look for stuff",`

Suggest this be edited to

> Plumbing to be able to look for stuff. For the command line tool, install App::Rak.

**Comment by coke** [comment]
Suggested because I've installed this twice now and been surprised.

**Comment by lizmat** [comment]
So done, thanks for the headsup!

**Comment by coke** [comment]
Thank you - would it make sense to do this in the META also, for 'zef info' ?
